version: "3.9"

services:
  app:
    tty: true
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./Opendata:/Opendata
    command: >
      sh -c "./entrypoint.sh"
    environment:
      - DB_USER=postgres
      - DB_PASS=0000
    depends_on:
      - redis
      - db

  db:
    image: postgres:13-alpine
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=0000

  redis:
    container_name: redis_service
    image: redis:alpine
    ports:
      - "6379:6379"

  rabbitmq:
    container_name: rabbitmq_service
    image: rabbitmq:3.7.14-management-alpine
    environment:
      - RABBITMQ_USER=guest
      - RABBITMQ_PASSWORD=guest
    ports:
      - "5672:5672"
      - "15672:15672"

  celery_worker:
    container_name: celery_worker
    build:
      context: .
    environment:
      - DB_USER=postgres
      - DB_PASS=0000
    volumes:
      - ./Opendata:/Opendata
    working_dir: /Opendata/
    command: >
      bash -c "celery -A Opendata worker --loglevel=info"
    depends_on:
      - app
      - rabbitmq

  celery_beat:
    container_name: celery_beat
    build:
      context: .
    environment:
      - DB_USER=postgres
      - DB_PASS=0000
    volumes:
      - ./Opendata:/Opendata
    working_dir: /Opendata/
    depends_on:
      - app
      - rabbitmq
      - celery_worker
    command: sh -c "celery -A Opendata beat --loglevel=info"

volumes:
  postgres-data:
