version: "3.9"

services:
  app:
    tty: true
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./Opendata:/Opendata
    command: >
      sh -c "python3 manage.py wait_for_db &&
            python3 manage.py migrate &&
            python3 manage.py runserver 0.0.0.0:8000"
    environment:
      - DB_USER=postgres
      - DB_PASS=0000
    depends_on:
      - db

  db:
    image: postgres:13-alpine
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=0000

volumes:
  postgres-data: