version: "3.9"

services:
  app:
    tty: true
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./Opendata:/Opendata
    command: >
      sh -c "./entrypoint.sh"
    environment:
      - DB_USER=postgres
      - DB_PASS=0000
    depends_on:
      - redis
      - db

  db:
    image: postgres:13-alpine
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=0000

  redis:
    container_name: redis_service
    image: redis:alpine
    ports:
      - "6379:6379"

volumes:
  postgres-data: